version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./ubuntu-ami.json
  build-base:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base
          command: 
            packer build \
            -var 'aws_access_key=AKIAXOQ3XLO2NVDRX3W7' \
            -var 'aws_secret_key=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' \
            -var 'aws_region=us-east-1' \
            -var 'subnet_id=' \
            -var 'nonprod_account_id=813034945358'\
            ubuntu-ami.json
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate