version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./ubuntu-ami.json
  build-base:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base
          command: 
            packer build -var-file=./vars.json -var 'AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' -var 'AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' ubuntu-ami.json 
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate